services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    volumes:
      - './ollama:/root/.ollama'
      
  redis-stack:
    image: redis/redis-stack
    environment:
       - TZ=Asia/Taipei
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./data:/data