spring:
  application:
    name: ollama-demo
  ai:
    ollama:
      baseUrl: http://localhost:11434
      chat:
        enabled: true
        options:
          model: deepseek-r1
      embedding:
        enabled: true
        options:
          model: nomic-embed-text
  neo4j:
    authentication:
      password: password
      username: neo4j
    uri: neo4j+s://localhost
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    initialization-mode: always
  jpa:
    show-sql: true
    open-in-view: false
#  sql:
#   init:
#     mode: always